<?php

namespace Company\BlogBundle\Controller;

require_once dirname(__FILE__) . '/../../../../../src/Company/BlogBundle/Controller/DefaultController.php';

/**
 * Test class for DefaultController.
 * Generated by PHPUnit on 2011-06-05 at 11:59:37.
 */
class DefaultControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DefaultController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DefaultController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testIndexAction().
     */
    public function testIndexAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
