<?php

namespace Acme\DemoBundle\Controller;

require_once dirname(__FILE__) . '/../../../../../src/Acme/DemoBundle/Controller/SecuredController.php';

/**
 * Test class for SecuredController.
 * Generated by PHPUnit on 2011-06-05 at 11:58:29.
 */
class SecuredControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SecuredController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SecuredController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testLoginAction().
     */
    public function testLoginAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSecurityCheckAction().
     */
    public function testSecurityCheckAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testLogoutAction().
     */
    public function testLogoutAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testHelloAction().
     */
    public function testHelloAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testHelloadminAction().
     */
    public function testHelloadminAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
