<?php

namespace Acme\DemoBundle\Controller;

require_once dirname(__FILE__) . '/../../../../../src/Acme/DemoBundle/Controller/WelcomeController.php';

/**
 * Test class for WelcomeController.
 * Generated by PHPUnit on 2011-06-05 at 11:58:29.
 */
class WelcomeControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var WelcomeController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WelcomeController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testIndexAction().
     */
    public function testIndexAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
